os: osx
dist: bionic
language: ruby
sudo: required
rvm:
  - 1.29.8
cache:
  apt: true
  yarn: true
  directories:
    - node_modules
    - "$HOME/.npm"
    - "$HOME/.cache"
before_install:
  - nvm install node
  - node --version
  - gem install bundler
install:
  - make install
script:
  - make check
  - make build