os: osx
language: ruby
rvm:
  - 2.5.1 # ruby version

addons:
  homebrew:
    update: true
    packages: 
    - $HOME/Library/Caches/Homebrew

cache:
  yarn: true
  directories:
    - node_modules
    - "$HOME/.npm"
    - "$HOME/.cache"

before_install:
  - brew install yarn
  - gem update --system
  - gem install bundler
  - gem install jekyll

install:
  - touch ctreffs.de.secrets.make # add dummy secrets
  - make install

script:
  - make check
  - make build