os: osx
dist: bionic
language: ruby
rvm:
  - 2.5.1 # ruby environment
addons:
homebrew:
  packages:
  - yarn
cache:
  apt: true
  yarn: true
  directories:
    - node_modules
    - "$HOME/.npm"
    - "$HOME/.cache"
before_install: # if "install" is overridden
  - gem install bundler
  - gem install jekyll
cache:
  yarn: true
install:
  - touch ctreffs.de.secrets.make # add dummy secrets
  - make install
script:
  - make check
  - make build