author: {github: ctreffs, location: Germany, name: Christian Treffs, twitter: chrisdailygrind}
baseurl: ''
email: webmaster@ctreffs.de
encoding: utf-8
exclude: [Gemfile, Gemfile.lock, README.md, package.json, publish.sh, yarn.lock, yarn-error.log]
font-awesome: {assets: true}
liquid: {error_mode: strict}
markdown: kramdown
plugins: [autoprefixer-rails, bootstrap, jekyll-feed, jekyll-font-awesome-sass]
profile_picture: https://secure.gravatar.com/avatar/6019de0fa6a933ee5282e1d623afd991?s=400
sass:
  load_paths: [_sass, node_modules]
social:
- github:
  - {name: ctreffs}
  - {url: 'https://github.com/ctreffs'}
strict_front_matter: true
timezone: Europe/Berlin
title: Christian Treffs
url: https://ctreffs.de