# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Build"
  Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      #- uses: actions/cache@v2
      #  with:
      #    path: vendor/bundle
      #    key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}


      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.3 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Setup
        run: |
          touch ctreffs.de.secrets.make # add dummy secrets
          brew install yarn
          make installYarn

      - name: Check
        run: make check
      
      - name: Build
        run: make build

      - name: Check markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@master
        with:
          folder-path: '_data, _drafts, _includes, _layouts, _pages, _posts, assets'
          file-path: './README.md, ./LICENSE.md, ./index.md'
